/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : MyGrammarTest.g
 *     -                            On : 2024-10-08 22:49:59
 *     -                 for the lexer : MyGrammarTestLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MyGrammarTestLexer.h"
/* ----------------------------------------- */


/** String literals used by MyGrammarTestLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x61, 0x72, 0x72, 0x61, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x62, 0x6F, 0x6F, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x62, 0x79, 0x74, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x63, 0x68, 0x61, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x6C, 0x6F, 0x6E, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x6F, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x73, 0x74, 0x72, 0x69, 0x6E, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x75, 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x75, 0x6C, 0x6F, 0x6E, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x74, 0x72, 0x75, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x66, 0x61, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMyGrammarTestLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMyGrammarTestLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMyGrammarTestLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMyGrammarTestLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__14    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__15    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__16    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__17    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__20    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__21    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__22    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__23    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__24    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__25    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__26    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__27    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__28    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mT__29    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mBOOL_LITERAL    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mIDENTIFIER    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_LIT    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mESC_SEQ    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mCHAR    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mHEX_LITERAL    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mHEX_DIGIT    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mBITS_LITERAL    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mDEC_LITERAL    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pMyGrammarTestLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pMyGrammarTestLexer ctx);
static void	MyGrammarTestLexerFree(pMyGrammarTestLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
MyGrammarTestLexerFree  (pMyGrammarTestLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
MyGrammarTestLexerReset (pMyGrammarTestLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "MyGrammarTest.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called MyGrammarTestLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pMyGrammarTestLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pMyGrammarTestLexer MyGrammarTestLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return MyGrammarTestLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called MyGrammarTestLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pMyGrammarTestLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pMyGrammarTestLexer MyGrammarTestLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMyGrammarTestLexer ctx; // Context structure we will build and return

    ctx = (pMyGrammarTestLexer) ANTLR3_CALLOC(1, sizeof(MyGrammarTestLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MyGrammarTestLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our MyGrammarTestLexer interface
     */
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mBOOL_LITERAL	= mBOOL_LITERAL;
    ctx->mIDENTIFIER	= mIDENTIFIER;
    ctx->mSTRING_LIT	= mSTRING_LIT;
    ctx->mESC_SEQ	= mESC_SEQ;
    ctx->mCHAR	= mCHAR;
    ctx->mHEX_LITERAL	= mHEX_LITERAL;
    ctx->mHEX_DIGIT	= mHEX_DIGIT;
    ctx->mBITS_LITERAL	= mBITS_LITERAL;
    ctx->mDEC_LITERAL	= mDEC_LITERAL;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= MyGrammarTestLexerFree;
    ctx->reset          = MyGrammarTestLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;


    // MyGrammarTest.g:7:7: ( '(' )
    // MyGrammarTest.g:7:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 8:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;


    // MyGrammarTest.g:8:7: ( ')' )
    // MyGrammarTest.g:8:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 9:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;


    // MyGrammarTest.g:9:7: ( ',' )
    // MyGrammarTest.g:9:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 10:7: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // MyGrammarTest.g:10:7: ( ':' )
    // MyGrammarTest.g:10:9: ':'
    {
        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 11:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // MyGrammarTest.g:11:7: ( '[' )
    // MyGrammarTest.g:11:9: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 12:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // MyGrammarTest.g:12:7: ( ']' )
    // MyGrammarTest.g:12:9: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 13:7: ( 'array' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;


    // MyGrammarTest.g:13:7: ( 'array' )
    // MyGrammarTest.g:13:9: 'array'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 14:7: ( 'bool' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;


    // MyGrammarTest.g:14:7: ( 'bool' )
    // MyGrammarTest.g:14:9: 'bool'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 15:7: ( 'byte' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;


    // MyGrammarTest.g:15:7: ( 'byte' )
    // MyGrammarTest.g:15:9: 'byte'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 16:7: ( 'char' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;


    // MyGrammarTest.g:16:7: ( 'char' )
    // MyGrammarTest.g:16:9: 'char'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 17:7: ( 'int' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;


    // MyGrammarTest.g:17:7: ( 'int' )
    // MyGrammarTest.g:17:9: 'int'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 18:7: ( 'long' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;


    // MyGrammarTest.g:18:7: ( 'long' )
    // MyGrammarTest.g:18:9: 'long'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 19:7: ( 'of' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;


    // MyGrammarTest.g:19:7: ( 'of' )
    // MyGrammarTest.g:19:9: 'of'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 20:7: ( 'string' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;


    // MyGrammarTest.g:20:7: ( 'string' )
    // MyGrammarTest.g:20:9: 'string'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 21:7: ( 'uint' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;


    // MyGrammarTest.g:21:7: ( 'uint' )
    // MyGrammarTest.g:21:9: 'uint'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 22:7: ( 'ulong' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;


    // MyGrammarTest.g:22:7: ( 'ulong' )
    // MyGrammarTest.g:22:9: 'ulong'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 9:14: ( 'true' | 'false' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BOOL_LITERAL
 *
 * Looks to match the characters the constitute the token BOOL_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBOOL_LITERAL(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BOOL_LITERAL;


    {
        //  MyGrammarTest.g:9:14: ( 'true' | 'false' )

        ANTLR3_UINT32 alt1;

        alt1=2;

        switch ( LA(1) )
        {
        case 't':
        	{
        		alt1=1;
        	}
            break;
        case 'f':
        	{
        		alt1=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 1;
            EXCEPTION->state        = 0;


            goto ruleBOOL_LITERALEx;

        }

        switch (alt1)
        {
    	case 1:
    	    // MyGrammarTest.g:9:16: 'true'
    	    {
    	        MATCHS(lit_11);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleBOOL_LITERALEx;
    	        }




    	    }
    	    break;
    	case 2:
    	    // MyGrammarTest.g:9:25: 'false'
    	    {
    	        MATCHS(lit_12);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleBOOL_LITERALEx;
    	        }




    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBOOL_LITERALEx; /* Prevent compiler warnings */
    ruleBOOL_LITERALEx: ;

}
// $ANTLR end BOOL_LITERAL

//   Comes from: 10:12: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IDENTIFIER
 *
 * Looks to match the characters the constitute the token IDENTIFIER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIDENTIFIER(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IDENTIFIER;


    // MyGrammarTest.g:10:12: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // MyGrammarTest.g:10:14: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleIDENTIFIEREx;
        }


        // MyGrammarTest.g:10:38: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt2=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2)
            {
        	case 1:
        	    // MyGrammarTest.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDENTIFIEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDENTIFIEREx; /* Prevent compiler warnings */
    ruleIDENTIFIEREx: ;

}
// $ANTLR end IDENTIFIER

//   Comes from: 11:12: ( '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_LIT
 *
 * Looks to match the characters the constitute the token STRING_LIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_LIT(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING_LIT;


    // MyGrammarTest.g:11:12: ( '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"' )
    // MyGrammarTest.g:11:14: '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITEx;
        }


        // MyGrammarTest.g:11:18: ( ESC_SEQ |~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt3=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA3_0 = LA(1);
                if ( (LA3_0 == '\\'))
                {
                    alt3=1;
                }
                else if ( (((LA3_0 >= 0x0000) && (LA3_0 <= '!')) || ((LA3_0 >= '#') && (LA3_0 <= '[')) || ((LA3_0 >= ']') && (LA3_0 <= 0xFFFF))))
                {
                    alt3=2;
                }

            }
            switch (alt3)
            {
        	case 1:
        	    // MyGrammarTest.g:11:20: ESC_SEQ
        	    {
        	        /* 11:20: ESC_SEQ */
        	        mESC_SEQ(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_LITEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // MyGrammarTest.g:11:30: ~ ( '\\\\' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleSTRING_LITEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */


        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRING_LITEx; /* Prevent compiler warnings */
    ruleSTRING_LITEx: ;

}
// $ANTLR end STRING_LIT

//   Comes from: 12:18: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ESC_SEQ
 *
 * Looks to match the characters the constitute the token ESC_SEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mESC_SEQ(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;


    // MyGrammarTest.g:12:18: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
    // MyGrammarTest.g:12:20: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
    {
        MATCHC('\\');
        if  (HASEXCEPTION())
        {
            goto ruleESC_SEQEx;
        }


        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleESC_SEQEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleESC_SEQEx; /* Prevent compiler warnings */
    ruleESC_SEQEx: ;

}
// $ANTLR end ESC_SEQ

//   Comes from: 13:6: ( '\\'' ( ESC_SEQ |~ ( '\\'' ) ) '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHAR
 *
 * Looks to match the characters the constitute the token CHAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHAR(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHAR;


    // MyGrammarTest.g:13:6: ( '\\'' ( ESC_SEQ |~ ( '\\'' ) ) '\\'' )
    // MyGrammarTest.g:13:8: '\\'' ( ESC_SEQ |~ ( '\\'' ) ) '\\''
    {
        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHAREx;
        }


        // MyGrammarTest.g:13:13: ( ESC_SEQ |~ ( '\\'' ) )
        {
            int alt4=2;
            {
                int LA4_0 = LA(1);
                if ( (LA4_0 == '\\'))
                {
                    switch ( LA(2) )
                    {
                    case '\'':
                    	{
                    		switch ( LA(3) )
                    		{
                    		case '\'':
                    			{
                    				alt4=1;
                    			}
                    		    break;

                    		default:
                    		    alt4=2;
                    		}

                    	}
                        break;
                    case '"':
                    case '\\':
                    case 'b':
                    case 'f':
                    case 'n':
                    case 'r':
                    case 't':
                    	{
                    		alt4=1;
                    	}
                        break;

                    default:
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 4;
                        EXCEPTION->state        = 1;


                        goto ruleCHAREx;

                    }

                }
                else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '&')) || ((LA4_0 >= '(') && (LA4_0 <= '[')) || ((LA4_0 >= ']') && (LA4_0 <= 0xFFFF))))
                {
                    alt4=2;
                }
                else
                {

                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 4;
                    EXCEPTION->state        = 0;


                    goto ruleCHAREx;

                }
            }
            switch (alt4)
            {
        	case 1:
        	    // MyGrammarTest.g:13:14: ESC_SEQ
        	    {
        	        /* 13:14: ESC_SEQ */
        	        mESC_SEQ(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCHAREx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // MyGrammarTest.g:13:24: ~ ( '\\'' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleCHAREx;
        	        }


        	    }
        	    break;

            }
        }

        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHAREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHAREx; /* Prevent compiler warnings */
    ruleCHAREx: ;

}
// $ANTLR end CHAR

//   Comes from: 14:13: ( '0' ( 'x' | 'X' ) ( HEX_DIGIT )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HEX_LITERAL
 *
 * Looks to match the characters the constitute the token HEX_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHEX_LITERAL(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = HEX_LITERAL;


    // MyGrammarTest.g:14:13: ( '0' ( 'x' | 'X' ) ( HEX_DIGIT )+ )
    // MyGrammarTest.g:14:15: '0' ( 'x' | 'X' ) ( HEX_DIGIT )+
    {
        MATCHC('0');
        if  (HASEXCEPTION())
        {
            goto ruleHEX_LITERALEx;
        }


        if ( LA(1) == 'X' || LA(1) == 'x' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleHEX_LITERALEx;
        }


        // MyGrammarTest.g:14:29: ( HEX_DIGIT )+
        {
            int cnt5=0;

            for (;;)
            {
                int alt5=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        		{
        			alt5=1;
        		}
        	    break;

        	}

        	switch (alt5)
        	{
        	    case 1:
        	        // MyGrammarTest.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'F')) || ((LA(1) >= 'a') && (LA(1) <= 'f')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleHEX_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt5 >= 1 )
        		{
        		    goto loop5;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleHEX_LITERALEx;
        	}
        	cnt5++;
            }
            loop5: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleHEX_LITERALEx; /* Prevent compiler warnings */
    ruleHEX_LITERALEx: ;

}
// $ANTLR end HEX_LITERAL

//   Comes from: 15:20: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HEX_DIGIT
 *
 * Looks to match the characters the constitute the token HEX_DIGIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHEX_DIGIT(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;


    // MyGrammarTest.g:15:20: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
    // MyGrammarTest.g:
    {
        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'F')) || ((LA(1) >= 'a') && (LA(1) <= 'f')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleHEX_DIGITEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleHEX_DIGITEx; /* Prevent compiler warnings */
    ruleHEX_DIGITEx: ;

}
// $ANTLR end HEX_DIGIT

//   Comes from: 16:14: ( '0' ( 'b' | 'B' ) ( '0' | '1' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BITS_LITERAL
 *
 * Looks to match the characters the constitute the token BITS_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBITS_LITERAL(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BITS_LITERAL;


    // MyGrammarTest.g:16:14: ( '0' ( 'b' | 'B' ) ( '0' | '1' )+ )
    // MyGrammarTest.g:16:16: '0' ( 'b' | 'B' ) ( '0' | '1' )+
    {
        MATCHC('0');
        if  (HASEXCEPTION())
        {
            goto ruleBITS_LITERALEx;
        }


        if ( LA(1) == 'B' || LA(1) == 'b' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleBITS_LITERALEx;
        }


        // MyGrammarTest.g:16:30: ( '0' | '1' )+
        {
            int cnt6=0;

            for (;;)
            {
                int alt6=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        		{
        			alt6=1;
        		}
        	    break;

        	}

        	switch (alt6)
        	{
        	    case 1:
        	        // MyGrammarTest.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '1')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleBITS_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt6 >= 1 )
        		{
        		    goto loop6;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleBITS_LITERALEx;
        	}
        	cnt6++;
            }
            loop6: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBITS_LITERALEx; /* Prevent compiler warnings */
    ruleBITS_LITERALEx: ;

}
// $ANTLR end BITS_LITERAL

//   Comes from: 17:13: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DEC_LITERAL
 *
 * Looks to match the characters the constitute the token DEC_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDEC_LITERAL(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DEC_LITERAL;


    // MyGrammarTest.g:17:13: ( ( '0' .. '9' )+ )
    // MyGrammarTest.g:17:15: ( '0' .. '9' )+
    {
        // MyGrammarTest.g:17:15: ( '0' .. '9' )+
        {
            int cnt7=0;

            for (;;)
            {
                int alt7=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt7=1;
        		}
        	    break;

        	}

        	switch (alt7)
        	{
        	    case 1:
        	        // MyGrammarTest.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleDEC_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt7 >= 1 )
        		{
        		    goto loop7;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleDEC_LITERALEx;
        	}
        	cnt7++;
            }
            loop7: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDEC_LITERALEx; /* Prevent compiler warnings */
    ruleDEC_LITERALEx: ;

}
// $ANTLR end DEC_LITERAL

//   Comes from: 18:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pMyGrammarTestLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // MyGrammarTest.g:18:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    // MyGrammarTest.g:18:9: ( ' ' | '\\t' | '\\r' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleWSEx;
        }


        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pMyGrammarTestLexer ctx)
{
    {
        //  MyGrammarTest.g:1:8: ( T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | BOOL_LITERAL | IDENTIFIER | STRING_LIT | CHAR | HEX_LITERAL | BITS_LITERAL | DEC_LITERAL | WS )

        ANTLR3_UINT32 alt8;

        alt8=24;

        switch ( LA(1) )
        {
        case '(':
        	{
        		alt8=1;
        	}
            break;
        case ')':
        	{
        		alt8=2;
        	}
            break;
        case ',':
        	{
        		alt8=3;
        	}
            break;
        case ':':
        	{
        		alt8=4;
        	}
            break;
        case '[':
        	{
        		alt8=5;
        	}
            break;
        case ']':
        	{
        		alt8=6;
        	}
            break;
        case 'a':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case 'a':
        							{
        								switch ( LA(5) )
        								{
        								case 'y':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt8=18;
        											}
        										    break;

        										default:
        										    alt8=7;
        										}

        									}
        								    break;

        								default:
        								    alt8=18;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'b':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'o':
        					{
        						switch ( LA(4) )
        						{
        						case 'l':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=18;
        									}
        								    break;

        								default:
        								    alt8=8;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;
        		case 'y':
        			{
        				switch ( LA(3) )
        				{
        				case 't':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=18;
        									}
        								    break;

        								default:
        								    alt8=9;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'a':
        					{
        						switch ( LA(4) )
        						{
        						case 'r':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=18;
        									}
        								    break;

        								default:
        								    alt8=10;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				switch ( LA(3) )
        				{
        				case 't':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt8=18;
        							}
        						    break;

        						default:
        						    alt8=11;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'l':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'n':
        					{
        						switch ( LA(4) )
        						{
        						case 'g':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=18;
        									}
        								    break;

        								default:
        								    alt8=12;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'o':
        	{
        		switch ( LA(2) )
        		{
        		case 'f':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case '_':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt8=18;
        					}
        				    break;

        				default:
        				    alt8=13;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 's':
        	{
        		switch ( LA(2) )
        		{
        		case 't':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case 'i':
        							{
        								switch ( LA(5) )
        								{
        								case 'n':
        									{
        										switch ( LA(6) )
        										{
        										case 'g':
        											{
        												switch ( LA(7) )
        												{
        												case '0':
        												case '1':
        												case '2':
        												case '3':
        												case '4':
        												case '5':
        												case '6':
        												case '7':
        												case '8':
        												case '9':
        												case 'A':
        												case 'B':
        												case 'C':
        												case 'D':
        												case 'E':
        												case 'F':
        												case 'G':
        												case 'H':
        												case 'I':
        												case 'J':
        												case 'K':
        												case 'L':
        												case 'M':
        												case 'N':
        												case 'O':
        												case 'P':
        												case 'Q':
        												case 'R':
        												case 'S':
        												case 'T':
        												case 'U':
        												case 'V':
        												case 'W':
        												case 'X':
        												case 'Y':
        												case 'Z':
        												case '_':
        												case 'a':
        												case 'b':
        												case 'c':
        												case 'd':
        												case 'e':
        												case 'f':
        												case 'g':
        												case 'h':
        												case 'i':
        												case 'j':
        												case 'k':
        												case 'l':
        												case 'm':
        												case 'n':
        												case 'o':
        												case 'p':
        												case 'q':
        												case 'r':
        												case 's':
        												case 't':
        												case 'u':
        												case 'v':
        												case 'w':
        												case 'x':
        												case 'y':
        												case 'z':
        													{
        														alt8=18;
        													}
        												    break;

        												default:
        												    alt8=14;
        												}

        											}
        										    break;

        										default:
        										    alt8=18;
        										}

        									}
        								    break;

        								default:
        								    alt8=18;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'u':
        	{
        		switch ( LA(2) )
        		{
        		case 'i':
        			{
        				switch ( LA(3) )
        				{
        				case 'n':
        					{
        						switch ( LA(4) )
        						{
        						case 't':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=18;
        									}
        								    break;

        								default:
        								    alt8=15;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;
        		case 'l':
        			{
        				switch ( LA(3) )
        				{
        				case 'o':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 'g':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt8=18;
        											}
        										    break;

        										default:
        										    alt8=16;
        										}

        									}
        								    break;

        								default:
        								    alt8=18;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 't':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'u':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt8=18;
        									}
        								    break;

        								default:
        								    alt8=17;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'a':
        			{
        				switch ( LA(3) )
        				{
        				case 'l':
        					{
        						switch ( LA(4) )
        						{
        						case 's':
        							{
        								switch ( LA(5) )
        								{
        								case 'e':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt8=18;
        											}
        										    break;

        										default:
        										    alt8=17;
        										}

        									}
        								    break;

        								default:
        								    alt8=18;
        								}

        							}
        						    break;

        						default:
        						    alt8=18;
        						}

        					}
        				    break;

        				default:
        				    alt8=18;
        				}

        			}
        		    break;

        		default:
        		    alt8=18;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'd':
        case 'e':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'm':
        case 'n':
        case 'p':
        case 'q':
        case 'r':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt8=18;
        	}
            break;
        case '"':
        	{
        		alt8=19;
        	}
            break;
        case '\'':
        	{
        		alt8=20;
        	}
            break;
        case '0':
        	{
        		switch ( LA(2) )
        		{
        		case 'X':
        		case 'x':
        			{
        				alt8=21;
        			}
        		    break;
        		case 'B':
        		case 'b':
        			{
        				alt8=22;
        			}
        		    break;

        		default:
        		    alt8=23;
        		}

        	}
            break;
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt8=23;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt8=24;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 8;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt8)
        {
    	case 1:
    	    // MyGrammarTest.g:1:10: T__14
    	    {
    	        /* 1:10: T__14 */
    	        mT__14(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // MyGrammarTest.g:1:16: T__15
    	    {
    	        /* 1:16: T__15 */
    	        mT__15(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // MyGrammarTest.g:1:22: T__16
    	    {
    	        /* 1:22: T__16 */
    	        mT__16(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // MyGrammarTest.g:1:28: T__17
    	    {
    	        /* 1:28: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // MyGrammarTest.g:1:34: T__18
    	    {
    	        /* 1:34: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // MyGrammarTest.g:1:40: T__19
    	    {
    	        /* 1:40: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // MyGrammarTest.g:1:46: T__20
    	    {
    	        /* 1:46: T__20 */
    	        mT__20(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // MyGrammarTest.g:1:52: T__21
    	    {
    	        /* 1:52: T__21 */
    	        mT__21(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // MyGrammarTest.g:1:58: T__22
    	    {
    	        /* 1:58: T__22 */
    	        mT__22(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // MyGrammarTest.g:1:64: T__23
    	    {
    	        /* 1:64: T__23 */
    	        mT__23(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // MyGrammarTest.g:1:70: T__24
    	    {
    	        /* 1:70: T__24 */
    	        mT__24(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // MyGrammarTest.g:1:76: T__25
    	    {
    	        /* 1:76: T__25 */
    	        mT__25(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // MyGrammarTest.g:1:82: T__26
    	    {
    	        /* 1:82: T__26 */
    	        mT__26(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // MyGrammarTest.g:1:88: T__27
    	    {
    	        /* 1:88: T__27 */
    	        mT__27(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // MyGrammarTest.g:1:94: T__28
    	    {
    	        /* 1:94: T__28 */
    	        mT__28(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // MyGrammarTest.g:1:100: T__29
    	    {
    	        /* 1:100: T__29 */
    	        mT__29(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // MyGrammarTest.g:1:106: BOOL_LITERAL
    	    {
    	        /* 1:106: BOOL_LITERAL */
    	        mBOOL_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // MyGrammarTest.g:1:119: IDENTIFIER
    	    {
    	        /* 1:119: IDENTIFIER */
    	        mIDENTIFIER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // MyGrammarTest.g:1:130: STRING_LIT
    	    {
    	        /* 1:130: STRING_LIT */
    	        mSTRING_LIT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // MyGrammarTest.g:1:141: CHAR
    	    {
    	        /* 1:141: CHAR */
    	        mCHAR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // MyGrammarTest.g:1:146: HEX_LITERAL
    	    {
    	        /* 1:146: HEX_LITERAL */
    	        mHEX_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // MyGrammarTest.g:1:158: BITS_LITERAL
    	    {
    	        /* 1:158: BITS_LITERAL */
    	        mBITS_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // MyGrammarTest.g:1:171: DEC_LITERAL
    	    {
    	        /* 1:171: DEC_LITERAL */
    	        mDEC_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // MyGrammarTest.g:1:183: WS
    	    {
    	        /* 1:183: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
