/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : MyGrammarTest.g
 *     -                            On : 2024-10-08 22:49:58
 *     -                for the parser : MyGrammarTestParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MyGrammarTestParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMyGrammarTestParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMyGrammarTestParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMyGrammarTestParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMyGrammarTestParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   MyGrammarTestParserTokenNames[26+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "BITS_LITERAL",
        (pANTLR3_UINT8) "BOOL_LITERAL",
        (pANTLR3_UINT8) "CHAR",
        (pANTLR3_UINT8) "DEC_LITERAL",
        (pANTLR3_UINT8) "ESC_SEQ",
        (pANTLR3_UINT8) "HEX_DIGIT",
        (pANTLR3_UINT8) "HEX_LITERAL",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "STRING_LIT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "':'",
        (pANTLR3_UINT8) "'['",
        (pANTLR3_UINT8) "']'",
        (pANTLR3_UINT8) "'array'",
        (pANTLR3_UINT8) "'bool'",
        (pANTLR3_UINT8) "'byte'",
        (pANTLR3_UINT8) "'char'",
        (pANTLR3_UINT8) "'int'",
        (pANTLR3_UINT8) "'long'",
        (pANTLR3_UINT8) "'of'",
        (pANTLR3_UINT8) "'string'",
        (pANTLR3_UINT8) "'uint'",
        (pANTLR3_UINT8) "'ulong'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 MyGrammarTestParser_list_item_return
	list_item    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_item_return
	item    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_typeRef_return
	typeRef    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_builtin_return
	builtin    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_custom_return
	custom    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_array_return
	array    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_funcSignature_return
	funcSignature    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_list_argDef_return
	list_argDef    (pMyGrammarTestParser ctx);
static 
 MyGrammarTestParser_argDef_return
	argDef    (pMyGrammarTestParser ctx);
static void	MyGrammarTestParserFree(pMyGrammarTestParser ctx);
static void     MyGrammarTestParserReset (pMyGrammarTestParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "MyGrammarTest.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new MyGrammarTestParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMyGrammarTestParser
MyGrammarTestParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return MyGrammarTestParserNewSSD(instream, NULL);
}

/** \brief Create a new MyGrammarTestParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMyGrammarTestParser
MyGrammarTestParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMyGrammarTestParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pMyGrammarTestParser) ANTLR3_CALLOC(1, sizeof(MyGrammarTestParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MyGrammarTestParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our MyGrammarTestParser interface
     */
    ctx->list_item	= list_item;
    ctx->item	= item;
    ctx->typeRef	= typeRef;
    ctx->builtin	= builtin;
    ctx->custom	= custom;
    ctx->array	= array;
    ctx->funcSignature	= funcSignature;
    ctx->list_argDef	= list_argDef;
    ctx->argDef	= argDef;
    ctx->free			= MyGrammarTestParserFree;
    ctx->reset			= MyGrammarTestParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = MyGrammarTestParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
MyGrammarTestParserReset (pMyGrammarTestParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 MyGrammarTestParserFree(pMyGrammarTestParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return MyGrammarTestParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_item_in_list_item260  */
static	ANTLR3_BITWORD FOLLOW_item_in_list_item260_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_item_in_list_item260	= { FOLLOW_item_in_list_item260_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_list_item263  */
static	ANTLR3_BITWORD FOLLOW_16_in_list_item263_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000014F0) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_list_item263	= { FOLLOW_16_in_list_item263_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_item_in_list_item265  */
static	ANTLR3_BITWORD FOLLOW_item_in_list_item265_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_item_in_list_item265	= { FOLLOW_item_in_list_item265_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_builtin_in_typeRef311  */
static	ANTLR3_BITWORD FOLLOW_builtin_in_typeRef311_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_builtin_in_typeRef311	= { FOLLOW_builtin_in_typeRef311_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_custom_in_typeRef315  */
static	ANTLR3_BITWORD FOLLOW_custom_in_typeRef315_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_custom_in_typeRef315	= { FOLLOW_custom_in_typeRef315_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_custom364  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_custom364_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_custom364	= { FOLLOW_IDENTIFIER_in_custom364_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_array374  */
static	ANTLR3_BITWORD FOLLOW_20_in_array374_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_array374	= { FOLLOW_20_in_array374_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_array376  */
static	ANTLR3_BITWORD FOLLOW_18_in_array376_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000090000) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_array376	= { FOLLOW_18_in_array376_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_array379  */
static	ANTLR3_BITWORD FOLLOW_16_in_array379_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000090000) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_array379	= { FOLLOW_16_in_array379_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_array383  */
static	ANTLR3_BITWORD FOLLOW_19_in_array383_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_array383	= { FOLLOW_19_in_array383_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_array385  */
static	ANTLR3_BITWORD FOLLOW_26_in_array385_bits[]	= { ANTLR3_UINT64_LIT(0x000000003BE00800) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_array385	= { FOLLOW_26_in_array385_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_typeRef_in_array387  */
static	ANTLR3_BITWORD FOLLOW_typeRef_in_array387_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_typeRef_in_array387	= { FOLLOW_typeRef_in_array387_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_funcSignature395  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_funcSignature395_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_funcSignature395	= { FOLLOW_IDENTIFIER_in_funcSignature395_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_funcSignature397  */
static	ANTLR3_BITWORD FOLLOW_14_in_funcSignature397_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008800) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_funcSignature397	= { FOLLOW_14_in_funcSignature397_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_argDef_in_funcSignature399  */
static	ANTLR3_BITWORD FOLLOW_list_argDef_in_funcSignature399_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_list_argDef_in_funcSignature399	= { FOLLOW_list_argDef_in_funcSignature399_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_funcSignature401  */
static	ANTLR3_BITWORD FOLLOW_15_in_funcSignature401_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_funcSignature401	= { FOLLOW_15_in_funcSignature401_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_funcSignature404  */
static	ANTLR3_BITWORD FOLLOW_17_in_funcSignature404_bits[]	= { ANTLR3_UINT64_LIT(0x000000003BE00800) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_funcSignature404	= { FOLLOW_17_in_funcSignature404_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_typeRef_in_funcSignature406  */
static	ANTLR3_BITWORD FOLLOW_typeRef_in_funcSignature406_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_typeRef_in_funcSignature406	= { FOLLOW_typeRef_in_funcSignature406_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_argDef_in_list_argDef419  */
static	ANTLR3_BITWORD FOLLOW_argDef_in_list_argDef419_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_argDef_in_list_argDef419	= { FOLLOW_argDef_in_list_argDef419_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_list_argDef422  */
static	ANTLR3_BITWORD FOLLOW_16_in_list_argDef422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_list_argDef422	= { FOLLOW_16_in_list_argDef422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_argDef_in_list_argDef424  */
static	ANTLR3_BITWORD FOLLOW_argDef_in_list_argDef424_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_argDef_in_list_argDef424	= { FOLLOW_argDef_in_list_argDef424_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_argDef438  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_argDef438_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_argDef438	= { FOLLOW_IDENTIFIER_in_argDef438_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_argDef441  */
static	ANTLR3_BITWORD FOLLOW_17_in_argDef441_bits[]	= { ANTLR3_UINT64_LIT(0x000000003BE00800) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_argDef441	= { FOLLOW_17_in_argDef441_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_typeRef_in_argDef443  */
static	ANTLR3_BITWORD FOLLOW_typeRef_in_argDef443_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_typeRef_in_argDef443	= { FOLLOW_typeRef_in_argDef443_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start list_item
 * MyGrammarTest.g:20:1: list_item : ( item ( ',' item )* )? ;
 */
static MyGrammarTestParser_list_item_return
list_item(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_list_item_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal2;
    MyGrammarTestParser_item_return item1;
    #undef	RETURN_TYPE_item1
    #define	RETURN_TYPE_item1 MyGrammarTestParser_item_return

    MyGrammarTestParser_item_return item3;
    #undef	RETURN_TYPE_item3
    #define	RETURN_TYPE_item3 MyGrammarTestParser_item_return

    pANTLR3_BASE_TREE char_literal2_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal2       = NULL;
    item1.tree = NULL;

    item3.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal2_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:20:11: ( ( item ( ',' item )* )? )
        // MyGrammarTest.g:20:13: ( item ( ',' item )* )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // MyGrammarTest.g:20:13: ( item ( ',' item )* )?
            {
                int alt2=2;
                switch ( LA(1) )
                {
                    case BITS_LITERAL:
                    case BOOL_LITERAL:
                    case CHAR:
                    case DEC_LITERAL:
                    case HEX_LITERAL:
                    case STRING_LIT:
                    	{
                    		alt2=1;
                    	}
                        break;
                }

                switch (alt2)
                {
            	case 1:
            	    // MyGrammarTest.g:20:14: item ( ',' item )*
            	    {
            	        FOLLOWPUSH(FOLLOW_item_in_list_item260);
            	        item1=item(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelist_itemEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, item1.tree);

            	        // MyGrammarTest.g:20:19: ( ',' item )*

            	        for (;;)
            	        {
            	            int alt1=2;
            	            switch ( LA(1) )
            	            {
            	            case 16:
            	            	{
            	            		alt1=1;
            	            	}
            	                break;

            	            }

            	            switch (alt1)
            	            {
            	        	case 1:
            	        	    // MyGrammarTest.g:20:20: ',' item
            	        	    {
            	        	        char_literal2 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_list_item263);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulelist_itemEx;
            	        	        }

            	        	        char_literal2_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal2));
            	        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal2_tree);


            	        	        FOLLOWPUSH(FOLLOW_item_in_list_item265);
            	        	        item3=item(ctx);

            	        	        FOLLOWPOP();
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulelist_itemEx;
            	        	        }

            	        	        ADAPTOR->addChild(ADAPTOR, root_0, item3.tree);

            	        	    }
            	        	    break;

            	        	default:
            	        	    goto loop1;	/* break out of the loop */
            	        	    break;
            	            }
            	        }
            	        loop1: ; /* Jump out to here if this rule does not match */


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto rulelist_itemEx; /* Prevent compiler warnings */
    rulelist_itemEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end list_item */

/**
 * $ANTLR start item
 * MyGrammarTest.g:21:10: fragment item : ( BOOL_LITERAL | CHAR | STRING_LIT | HEX_LITERAL | BITS_LITERAL | DEC_LITERAL ) ;
 */
static MyGrammarTestParser_item_return
item(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_item_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set4;

    pANTLR3_BASE_TREE set4_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    set4       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set4_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:21:15: ( ( BOOL_LITERAL | CHAR | STRING_LIT | HEX_LITERAL | BITS_LITERAL | DEC_LITERAL ) )
        // MyGrammarTest.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            set4=(pANTLR3_COMMON_TOKEN)LT(1);

            if ( ((LA(1) >= BITS_LITERAL) && (LA(1) <= DEC_LITERAL)) || LA(1) == HEX_LITERAL || LA(1) == STRING_LIT )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, 
                (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set4))
                );
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto ruleitemEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleitemEx; /* Prevent compiler warnings */
    ruleitemEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end item */

/**
 * $ANTLR start typeRef
 * MyGrammarTest.g:23:1: typeRef : ( builtin | custom ) ;
 */
static MyGrammarTestParser_typeRef_return
typeRef(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_typeRef_return retval;


    pANTLR3_BASE_TREE root_0;

    MyGrammarTestParser_builtin_return builtin5;
    #undef	RETURN_TYPE_builtin5
    #define	RETURN_TYPE_builtin5 MyGrammarTestParser_builtin_return

    MyGrammarTestParser_custom_return custom6;
    #undef	RETURN_TYPE_custom6
    #define	RETURN_TYPE_custom6 MyGrammarTestParser_custom_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    builtin5.tree = NULL;

    custom6.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // MyGrammarTest.g:23:9: ( ( builtin | custom ) )
        // MyGrammarTest.g:23:11: ( builtin | custom )
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // MyGrammarTest.g:23:11: ( builtin | custom )
            {
                int alt3=2;
                switch ( LA(1) )
                {
                case 21:
                case 22:
                case 23:
                case 24:
                case 25:
                case 27:
                case 28:
                case 29:
                	{
                		alt3=1;
                	}
                    break;
                case IDENTIFIER:
                	{
                		alt3=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 3;
                    EXCEPTION->state        = 0;


                    goto ruletypeRefEx;

                }

                switch (alt3)
                {
            	case 1:
            	    // MyGrammarTest.g:23:12: builtin
            	    {
            	        FOLLOWPUSH(FOLLOW_builtin_in_typeRef311);
            	        builtin5=builtin(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypeRefEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, builtin5.tree);

            	    }
            	    break;
            	case 2:
            	    // MyGrammarTest.g:23:22: custom
            	    {
            	        FOLLOWPUSH(FOLLOW_custom_in_typeRef315);
            	        custom6=custom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypeRefEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, custom6.tree);

            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruletypeRefEx; /* Prevent compiler warnings */
    ruletypeRefEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end typeRef */

/**
 * $ANTLR start builtin
 * MyGrammarTest.g:24:10: fragment builtin : ( 'bool' | 'byte' | 'int' | 'uint' | 'long' | 'ulong' | 'char' | 'string' ) ;
 */
static MyGrammarTestParser_builtin_return
builtin(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_builtin_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set7;

    pANTLR3_BASE_TREE set7_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    set7       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set7_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:24:18: ( ( 'bool' | 'byte' | 'int' | 'uint' | 'long' | 'ulong' | 'char' | 'string' ) )
        // MyGrammarTest.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            set7=(pANTLR3_COMMON_TOKEN)LT(1);

            if ( ((LA(1) >= 21) && (LA(1) <= 25)) || ((LA(1) >= 27) && (LA(1) <= 29)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, 
                (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set7))
                );
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto rulebuiltinEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulebuiltinEx; /* Prevent compiler warnings */
    rulebuiltinEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end builtin */

/**
 * $ANTLR start custom
 * MyGrammarTest.g:25:10: fragment custom : IDENTIFIER ;
 */
static MyGrammarTestParser_custom_return
custom(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_custom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    IDENTIFIER8;

    pANTLR3_BASE_TREE IDENTIFIER8_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    IDENTIFIER8       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    IDENTIFIER8_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:25:17: ( IDENTIFIER )
        // MyGrammarTest.g:25:19: IDENTIFIER
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            IDENTIFIER8 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_custom364);
            if  (HASEXCEPTION())
            {
                goto rulecustomEx;
            }

            IDENTIFIER8_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, IDENTIFIER8));
            ADAPTOR->addChild(ADAPTOR, root_0, IDENTIFIER8_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulecustomEx; /* Prevent compiler warnings */
    rulecustomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end custom */

/**
 * $ANTLR start array
 * MyGrammarTest.g:26:10: fragment array : 'array' '[' ( ',' )* ']' 'of' typeRef ;
 */
static MyGrammarTestParser_array_return
array(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_array_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal9;
    pANTLR3_COMMON_TOKEN    char_literal10;
    pANTLR3_COMMON_TOKEN    char_literal11;
    pANTLR3_COMMON_TOKEN    char_literal12;
    pANTLR3_COMMON_TOKEN    string_literal13;
    MyGrammarTestParser_typeRef_return typeRef14;
    #undef	RETURN_TYPE_typeRef14
    #define	RETURN_TYPE_typeRef14 MyGrammarTestParser_typeRef_return

    pANTLR3_BASE_TREE string_literal9_tree;
    pANTLR3_BASE_TREE char_literal10_tree;
    pANTLR3_BASE_TREE char_literal11_tree;
    pANTLR3_BASE_TREE char_literal12_tree;
    pANTLR3_BASE_TREE string_literal13_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    string_literal9       = NULL;
    char_literal10       = NULL;
    char_literal11       = NULL;
    char_literal12       = NULL;
    string_literal13       = NULL;
    typeRef14.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    string_literal9_tree   = NULL;
    char_literal10_tree   = NULL;
    char_literal11_tree   = NULL;
    char_literal12_tree   = NULL;
    string_literal13_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:26:16: ( 'array' '[' ( ',' )* ']' 'of' typeRef )
        // MyGrammarTest.g:26:18: 'array' '[' ( ',' )* ']' 'of' typeRef
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            string_literal9 = (pANTLR3_COMMON_TOKEN) MATCHT(20, &FOLLOW_20_in_array374);
            if  (HASEXCEPTION())
            {
                goto rulearrayEx;
            }

            string_literal9_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal9));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal9_tree);


            char_literal10 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_array376);
            if  (HASEXCEPTION())
            {
                goto rulearrayEx;
            }

            char_literal10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal10));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal10_tree);


            // MyGrammarTest.g:26:30: ( ',' )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case 16:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // MyGrammarTest.g:26:31: ','
            	    {
            	        char_literal11 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_array379);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulearrayEx;
            	        }

            	        char_literal11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal11));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal11_tree);


            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


            char_literal12 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_array383);
            if  (HASEXCEPTION())
            {
                goto rulearrayEx;
            }

            char_literal12_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal12));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal12_tree);


            string_literal13 = (pANTLR3_COMMON_TOKEN) MATCHT(26, &FOLLOW_26_in_array385);
            if  (HASEXCEPTION())
            {
                goto rulearrayEx;
            }

            string_literal13_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal13));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal13_tree);


            FOLLOWPUSH(FOLLOW_typeRef_in_array387);
            typeRef14=typeRef(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulearrayEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, typeRef14.tree);

        }

    }

    // This is where rules clean up and exit
    //
    goto rulearrayEx; /* Prevent compiler warnings */
    rulearrayEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end array */

/**
 * $ANTLR start funcSignature
 * MyGrammarTest.g:28:1: funcSignature : IDENTIFIER '(' list_argDef ')' ( ':' typeRef )? ;
 */
static MyGrammarTestParser_funcSignature_return
funcSignature(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_funcSignature_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    IDENTIFIER15;
    pANTLR3_COMMON_TOKEN    char_literal16;
    pANTLR3_COMMON_TOKEN    char_literal18;
    pANTLR3_COMMON_TOKEN    char_literal19;
    MyGrammarTestParser_list_argDef_return list_argDef17;
    #undef	RETURN_TYPE_list_argDef17
    #define	RETURN_TYPE_list_argDef17 MyGrammarTestParser_list_argDef_return

    MyGrammarTestParser_typeRef_return typeRef20;
    #undef	RETURN_TYPE_typeRef20
    #define	RETURN_TYPE_typeRef20 MyGrammarTestParser_typeRef_return

    pANTLR3_BASE_TREE IDENTIFIER15_tree;
    pANTLR3_BASE_TREE char_literal16_tree;
    pANTLR3_BASE_TREE char_literal18_tree;
    pANTLR3_BASE_TREE char_literal19_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    IDENTIFIER15       = NULL;
    char_literal16       = NULL;
    char_literal18       = NULL;
    char_literal19       = NULL;
    list_argDef17.tree = NULL;

    typeRef20.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    IDENTIFIER15_tree   = NULL;
    char_literal16_tree   = NULL;
    char_literal18_tree   = NULL;
    char_literal19_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:28:15: ( IDENTIFIER '(' list_argDef ')' ( ':' typeRef )? )
        // MyGrammarTest.g:28:17: IDENTIFIER '(' list_argDef ')' ( ':' typeRef )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            IDENTIFIER15 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_funcSignature395);
            if  (HASEXCEPTION())
            {
                goto rulefuncSignatureEx;
            }

            IDENTIFIER15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, IDENTIFIER15));
            ADAPTOR->addChild(ADAPTOR, root_0, IDENTIFIER15_tree);


            char_literal16 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_funcSignature397);
            if  (HASEXCEPTION())
            {
                goto rulefuncSignatureEx;
            }

            char_literal16_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal16));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal16_tree);


            FOLLOWPUSH(FOLLOW_list_argDef_in_funcSignature399);
            list_argDef17=list_argDef(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefuncSignatureEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, list_argDef17.tree);

            char_literal18 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_funcSignature401);
            if  (HASEXCEPTION())
            {
                goto rulefuncSignatureEx;
            }

            char_literal18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal18));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal18_tree);


            // MyGrammarTest.g:28:48: ( ':' typeRef )?
            {
                int alt5=2;
                switch ( LA(1) )
                {
                    case 17:
                    	{
                    		alt5=1;
                    	}
                        break;
                }

                switch (alt5)
                {
            	case 1:
            	    // MyGrammarTest.g:28:49: ':' typeRef
            	    {
            	        char_literal19 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_funcSignature404);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefuncSignatureEx;
            	        }

            	        char_literal19_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal19));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal19_tree);


            	        FOLLOWPUSH(FOLLOW_typeRef_in_funcSignature406);
            	        typeRef20=typeRef(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefuncSignatureEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, typeRef20.tree);

            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto rulefuncSignatureEx; /* Prevent compiler warnings */
    rulefuncSignatureEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end funcSignature */

/**
 * $ANTLR start list_argDef
 * MyGrammarTest.g:29:10: fragment list_argDef : ( argDef ( ',' argDef )* )? ;
 */
static MyGrammarTestParser_list_argDef_return
list_argDef(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_list_argDef_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal22;
    MyGrammarTestParser_argDef_return argDef21;
    #undef	RETURN_TYPE_argDef21
    #define	RETURN_TYPE_argDef21 MyGrammarTestParser_argDef_return

    MyGrammarTestParser_argDef_return argDef23;
    #undef	RETURN_TYPE_argDef23
    #define	RETURN_TYPE_argDef23 MyGrammarTestParser_argDef_return

    pANTLR3_BASE_TREE char_literal22_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal22       = NULL;
    argDef21.tree = NULL;

    argDef23.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal22_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:29:22: ( ( argDef ( ',' argDef )* )? )
        // MyGrammarTest.g:29:24: ( argDef ( ',' argDef )* )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // MyGrammarTest.g:29:24: ( argDef ( ',' argDef )* )?
            {
                int alt7=2;
                switch ( LA(1) )
                {
                    case IDENTIFIER:
                    	{
                    		alt7=1;
                    	}
                        break;
                }

                switch (alt7)
                {
            	case 1:
            	    // MyGrammarTest.g:29:25: argDef ( ',' argDef )*
            	    {
            	        FOLLOWPUSH(FOLLOW_argDef_in_list_argDef419);
            	        argDef21=argDef(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelist_argDefEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, argDef21.tree);

            	        // MyGrammarTest.g:29:32: ( ',' argDef )*

            	        for (;;)
            	        {
            	            int alt6=2;
            	            switch ( LA(1) )
            	            {
            	            case 16:
            	            	{
            	            		alt6=1;
            	            	}
            	                break;

            	            }

            	            switch (alt6)
            	            {
            	        	case 1:
            	        	    // MyGrammarTest.g:29:33: ',' argDef
            	        	    {
            	        	        char_literal22 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_list_argDef422);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulelist_argDefEx;
            	        	        }

            	        	        char_literal22_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal22));
            	        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal22_tree);


            	        	        FOLLOWPUSH(FOLLOW_argDef_in_list_argDef424);
            	        	        argDef23=argDef(ctx);

            	        	        FOLLOWPOP();
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulelist_argDefEx;
            	        	        }

            	        	        ADAPTOR->addChild(ADAPTOR, root_0, argDef23.tree);

            	        	    }
            	        	    break;

            	        	default:
            	        	    goto loop6;	/* break out of the loop */
            	        	    break;
            	            }
            	        }
            	        loop6: ; /* Jump out to here if this rule does not match */


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto rulelist_argDefEx; /* Prevent compiler warnings */
    rulelist_argDefEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end list_argDef */

/**
 * $ANTLR start argDef
 * MyGrammarTest.g:30:10: fragment argDef : IDENTIFIER ( ':' typeRef )? ;
 */
static MyGrammarTestParser_argDef_return
argDef(pMyGrammarTestParser ctx)
{
    MyGrammarTestParser_argDef_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    IDENTIFIER24;
    pANTLR3_COMMON_TOKEN    char_literal25;
    MyGrammarTestParser_typeRef_return typeRef26;
    #undef	RETURN_TYPE_typeRef26
    #define	RETURN_TYPE_typeRef26 MyGrammarTestParser_typeRef_return

    pANTLR3_BASE_TREE IDENTIFIER24_tree;
    pANTLR3_BASE_TREE char_literal25_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    IDENTIFIER24       = NULL;
    char_literal25       = NULL;
    typeRef26.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    IDENTIFIER24_tree   = NULL;
    char_literal25_tree   = NULL;


    retval.tree  = NULL;

    {
        // MyGrammarTest.g:30:17: ( IDENTIFIER ( ':' typeRef )? )
        // MyGrammarTest.g:30:19: IDENTIFIER ( ':' typeRef )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            IDENTIFIER24 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_argDef438);
            if  (HASEXCEPTION())
            {
                goto ruleargDefEx;
            }

            IDENTIFIER24_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, IDENTIFIER24));
            ADAPTOR->addChild(ADAPTOR, root_0, IDENTIFIER24_tree);


            // MyGrammarTest.g:30:30: ( ':' typeRef )?
            {
                int alt8=2;
                switch ( LA(1) )
                {
                    case 17:
                    	{
                    		alt8=1;
                    	}
                        break;
                }

                switch (alt8)
                {
            	case 1:
            	    // MyGrammarTest.g:30:31: ':' typeRef
            	    {
            	        char_literal25 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_argDef441);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleargDefEx;
            	        }

            	        char_literal25_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal25));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal25_tree);


            	        FOLLOWPUSH(FOLLOW_typeRef_in_argDef443);
            	        typeRef26=typeRef(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleargDefEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, typeRef26.tree);

            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleargDefEx; /* Prevent compiler warnings */
    ruleargDefEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end argDef */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
